config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users
  resources :users, only: :index
  root 'pages#home'
  get 'pages/home' => 'pages#home'
  get 'pages/dashboard' => 'pages#dashboard'
  
  get 'candidatos/selection' => 'candidatos#selection'
  post 'candidatos/selection' => 'candidatos#filter'
  get 'entrevistas/aprovar' => 'entrevistas#aprovar'
  
  get 'entrevistas/criteria_selection' => 'entrevistas#criteria_selection'
  post 'entrevistas/criteria_selection' => 'entrevistas#criteria_filter'
  
  resources :candidatos do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'entrevistas/selection' => 'entrevistas#selection'
  post 'entrevistas/selection' => 'entrevistas#filter'
  resources :entrevistas do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'formulario/:key' => 'pesquisas#matchKey'
  get 'pesquisas/enviar' => 'pesquisas#enviarForms'
  
  get 'pesquisas/selection' => 'pesquisas#selection'
  post 'pesquisas/selection' => 'pesquisas#filter'
  resources :pesquisas do
    collection { post :import }
    collection { get :addfile }
  end
  
  resources :candidatos
  get 'candidatos_pdfexport' => 'candidatos#pdfexport'
  

end

app/models/entrevista.rb
class Entrevista < ActiveRecord::Base
    belongs_to :candidato
    
    #validates :entregou_documentos, presence: true
    #validates :historico_escolar, presence: true
    #validates :numero_de_pessoas, presence: true
    #validates_presence_of :holerites_mes1, :if => :nenhuma_renda?
    #validates :agua_mes1, presence: true
    #validates :luz_mes1, presence: true
    
    def nenhuma_renda?
        aposentadorias.try(:empty?) || auxilios.try(:empty?)
    end
    
    validates_presence_of :holerites_mes1, :agua_mes1, :luz_mes1, :net_TV_mes1
    
    def self.media(arg1, arg2, arg3)
       result = 0
       numArgsNaoNulos = 0
       if(!arg1.nil?)
           result += arg1
           numArgsNaoNulos += 1
       end
       if(!arg2.nil?)
           result += arg2
           numArgsNaoNulos += 1
       end
       if(!arg3.nil?)
           result += arg3
           numArgsNaoNulos += 1
       end
       if(numArgsNaoNulos != 0)
        return result/numArgsNaoNulos
       else
        return 0
       end
    end
end

app/controllers/entrevistas_controller.rb
class EntrevistasController < ApplicationController
  before_action :set_entrevista, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /entrevistas
  # GET /entrevistas.json
  
  def index
    @entrevistas = Entrevista.all
  end

  # GET /entrevistas/1
  # GET /entrevistas/1.json
  def show
  end

  # GET /entrevistas/new
  def new
    @candidato = Candidato.find(params[:candidato_id])
    @entrevista = Entrevista.new
  end
  
  def criteria_selection
  end
  
  def aprovar
    @entrevistas_id = params[:entrevistas_id]
    @entrevistas = []
    Entrevista.all.each do |entrevista|
      entrevista.update(aprovado: false)
    end
    @entrevistas_id.each do |entrevista_id|
      @entrevista = Entrevista.find(entrevista_id)
      @entrevista.update(aprovado: true)
    end
    
    respond_to do |format|
      format.html { redirect_to entrevistas_url, notice: 'Status dos candidatos selecionados foi mudada para aprovado.' }
      format.json { head :no_content }
    end
    
  end
  
  def criteria_filter
    @columns = Entrevista.column_names
    @iptu = params[:iptu]
    @rlpc_max = params[:rlpc_max]
    @rlpc_min = params[:rlpc_min]
    @rbpc_max = params[:rbpc_max]
    @rbpc_min = params[:rbpc_min]
    @veiculos = params[:veiculos]
    @entrevistas = Entrevista.where("iptu < ? AND rlpc > ? AND rlpc < ? AND rbpc > ? AND rbpc < ? AND veiculos < ?", @iptu, @rlpc_min, @rlpc_max, @rbpc_min, @rbpc_max, @veiculos)
    @entrevistas_id = []
    @entrevistas.all.each do |entrevista|
      @entrevistas_id += [entrevista.id]
    end
    render :index3
  end
  
  def selection
    @atributos = Entrevista.column_names
  end
  def filter
    @columns = params[:exibir]
    @entrevistas = Entrevista.select(params[:exibir])
    render :index2
  end

  # GET /entrevistas/1/edit
  def edit
    @candidato = @pesquisa.candidato
  end

  # POST /entrevistas
  # POST /entrevistas.json
  def create
    @entrevista = Entrevista.new(entrevista_params)
    @candidato = Candidato.find(entrevista_params[:candidato_id])
    @entrevista.candidato = @candidato 
    respond_to do |format|
      if @entrevista.save
        format.html { redirect_to @entrevista, notice: 'Entrevista was successfully created.' }
        format.json { render :show, status: :created, location: @entrevista }
      else
        format.html { render :new }
        format.json { render json: @entrevista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrevistas/1
  # PATCH/PUT /entrevistas/1.json
  def update
    @candidato = @entrevista.candidato
    respond_to do |format|
      if @entrevista.update(entrevista_params)
        format.html { redirect_to @entrevista, notice: 'Entrevista was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrevista }
      else
        format.html { render :edit }
        format.json { render json: @entrevista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrevistas/1
  # DELETE /entrevistas/1.json
  def destroy
    @entrevista.destroy
    respond_to do |format|
      format.html { redirect_to entrevistas_url, notice: 'Entrevista was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrevista
      @entrevista = Entrevista.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrevista_params
      params.require(:entrevista).permit(:candidato_id, :entregou_documentos, :historico_escolar, :numero_de_pessoas, :iptu, :veiculos, :holerites_mes1, :holerites_mes2, :holerites_mes3, :aposentadorias, :auxilios, :renda_bruta, :rbpc, :agua_mes1, :agua_mes2, :agua_mes3, :luz_mes1, :luz_mes2, :luz_mes3, :net_TV_mes1, :net_TV_mes2, :net_TV_mes3, :aluguel, :outros_gastos, :gastos_totais, :renda_liq, :rlpc, :obs, :aprovado)
    end
end

app/helpers/entrevistas_helper.rb
module EntrevistasHelper
end

app/views/entrevistas/criteria_selection.html.erb
<%= form_tag("/entrevistas/criteria_selection", method: "post") do %>
  <h1>Preencher critérios</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="input-group">
        <span class="input-group-addon">Renda Líquida máxima per capita</span>
        <span class="input-group-addon">
          <%= number_field_tag(:rlpc_max, 5000 , autocomplete: "on") %>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="input-group">
        <span class="input-group-addon">Renda Líquida mínima per capita</span>
        <span class="input-group-addon">
          <%= number_field_tag(:rlpc_min, 0 , autocomplete: "on") %>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="input-group">
        <span class="input-group-addon">Renda Bruta máxima per capita</span>
        <span class="input-group-addon">
          <%= number_field_tag(:rbpc_max, 5000 , autocomplete: "on") %>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="input-group">
        <span class="input-group-addon">Renda Bruta mínima per capita</span>
        <span class="input-group-addon">
          <%= number_field_tag(:rbpc_min, 0 , autocomplete: "on") %>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>
  <br>
   <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="input-group">
        <span class="input-group-addon">Valor máximo de IPTU</span>
        <span class="input-group-addon">
          <%= number_field_tag(:iptu, 5000 , autocomplete: "on") %>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>
  <br>
   <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="input-group">
        <span class="input-group-addon">Máximo de patrimônio dos veículos</span>
        <span class="input-group-addon">
          <%= number_field_tag(:veiculos, 5000 , autocomplete: "on") %>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <%= submit_tag("Exibir" , role: "button", class: "btn btn-default center-block" ) %>
    </div>
  </div>
<% end %>

app/views/entrevistas/edit.html.erb
<div class="container">
    <br>
    <h1 class="text-center">Editar entrevista</h1>
    <br><br>
    <%= render 'form' %>
    <div></div>
    <div class="col-md-2 col-md-offset-5">
         <div class="center-block">
            <%= link_to 'Voltar', entrevistas_path, :class=>"btn btn-sm btn-default center-block" %>
        </div>
    </div>
</div>

app/views/entrevistas/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script>
  $(document).ready(function() {
  $('#entrevistasTable').DataTable();
});
</script>

<h1>Listando Entrevistas | <%= link_to "Selecionar Colunas", entrevistas_selection_path , role: "button", class: "btn btn-default"  %> | <%= link_to "Selecionar Critérios", entrevistas_criteria_selection_path , role: "button", class: "btn btn-default"  %></h1>
<br><br>
  <table class="table table-striped" id="entrevistasTable">
    <thead>
      <tr>
        <th>Entregou documentos</th>
        <th>Historico escolar</th>
        <th>Numero de pessoas</th>
        <th>Iptu</th>
        <th>Veiculos</th>
        <!--<th>Média Holerites</th>
        <th>Holerites mes1</th>
        <th>Holerites mes2</th>
        <th>Holerites mes3</th>
        <th>Aposentadorias</th>
        <th>Auxilios</th>-->
        <th>Renda bruta</th>
        <th>Renda bruta per capita</th>
        <!--<th>Média Agua</th>
        <th>Agua mes1</th>
        <th>Agua mes2</th>
        <th>Agua mes3</th>
        <th>Média Luz</th>
        <!--<th>Luz mes1</th>
        <th>Luz mes2</th>
        <th>Luz mes3</th>
        <th>Média Net/TV</th>
        <!--<th>Net tv mes1</th>
        <th>Net tv mes2</th>
        <th>Net tv mes3</th>
        <th>Aluguel</th>
        <th>Outros gastos</th>-->
        <th>Gastos totais</th>
        <th>Renda liq</th>
        <th>Rlpc</th>
        <th>Obs</th>
        <th>Aprovado</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @entrevistas.each do |entrevista| %>
        <tr>
          <td><%= entrevista.entregou_documentos %></td>
          <td><%= entrevista.historico_escolar %></td>
          <td><%= entrevista.numero_de_pessoas %></td>
          <td><%= entrevista.iptu %></td>
          <td><%= entrevista.veiculos %></td>
          <!--<td><%= Entrevista.media(entrevista.holerites_mes1, entrevista.holerites_mes2, entrevista.holerites_mes3) %></td>
          <td><%= entrevista.holerites_mes1 %></td>
          <td><%= entrevista.holerites_mes2 %></td>
          <td><%= entrevista.holerites_mes3 %></td>
          <td><%= entrevista.aposentadorias %></td>
          <td><%= entrevista.auxilios %></td>-->
          <td><%= entrevista.renda_bruta %></td>
          <td><%= entrevista.rbpc %></td>
          <!--<td><%= Entrevista.media(entrevista.agua_mes1, entrevista.agua_mes2, entrevista.agua_mes3) %></td>
          <td><%= Entrevista.media(entrevista.luz_mes1, entrevista.luz_mes2, entrevista.luz_mes3) %></td>
          <td><%= Entrevista.media(entrevista.net_TV_mes1, entrevista.net_TV_mes2, entrevista.net_TV_mes3) %></td>
          <td><%= entrevista.agua_mes1 %></td>
          <td><%= entrevista.agua_mes2 %></td>
          <td><%= entrevista.agua_mes3 %></td>
          <td><%= entrevista.luz_mes1 %></td>
          <td><%= entrevista.luz_mes2 %></td>
          <td><%= entrevista.luz_mes3 %></td>
          <td><%= entrevista.net_TV_mes1 %></td>
          <td><%= entrevista.net_TV_mes2 %></td>
          <td><%= entrevista.net_TV_mes3 %></td>
          <td><%= entrevista.aluguel %></td>
          <td><%= entrevista.outros_gastos %></td>-->
          <td><%= entrevista.gastos_totais %></td>
          <td><%= entrevista.renda_liq %></td>
          <td><%= entrevista.rlpc %></td>
          <td><%= entrevista.obs %></td>
          <td><%= entrevista.aprovado %></td>
          <td><%= link_to 'Ver', entrevista, :class => "btn btn-default btn-sm"%></td>
          <td><%= link_to 'Editar', edit_entrevista_path(entrevista), :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Excluir', entrevista, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>

</div>

app/views/entrevistas/index2.html.erb
<p id="notice"><%= notice %></p>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script>
  $(document).ready(function() {
  $('#entrevistasTable').DataTable();
});
</script>

<h1>Listando Entrevistas | <%= link_to "Selecionar Colunas", entrevistas_selection_path , role: "button", class: "btn btn-default"  %></h1>

<table id="entrevistasTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <% @columns.each do |s| %>
        <th><%= s.camelcase %></th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entrevistas.each do |entrevista| %>
      <tr>
        <% @columns.each do |s| %>
          <td><%= entrevista[s.to_sym] %></td>
        <% end %>
        <td><%= link_to 'Show', entrevista, role: "button", class: "btn btn-primary btn-xs"  %></td>
        <td><%= link_to 'Edit', edit_entrevista_path(entrevista), role: "button", class: "btn btn-info btn-xs"  %></td>
        <td><%= link_to 'Destroy', entrevista, method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class: "btn btn-danger btn-xs"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/entrevistas/index3.html.erb
<p id="notice"><%= notice %></p>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script>
  $(document).ready(function() {
  $('#entrevistasTable').DataTable();
});
</script>

<h1>Listando Entrevistas | <%= link_to "Selecionar Colunas", entrevistas_selection_path , role: "button", class: "btn btn-default"  %> | <%= link_to "Selecionar Critérios", entrevistas_criteria_selection_path , role: "button", class: "btn btn-default"  %></h1>
<h4>Número de candidatos: <%= @entrevistas.size %></h4>
<table id="entrevistasTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <% @columns.each do |s| %>
        <th><%= s.camelcase %></th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entrevistas.each do |entrevista| %>
      <tr>
        <% @columns.each do |s| %>
          <td><%= entrevista[s.to_sym] %></td>
        <% end %>
        <td><%= link_to 'Show', entrevista, role: "button", class: "btn btn-primary btn-xs"  %></td>
        <td><%= link_to 'Edit', edit_entrevista_path(entrevista), role: "button", class: "btn btn-info btn-xs"  %></td>
        <td><%= link_to 'Destroy', entrevista, method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class: "btn btn-danger btn-xs"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 <div class="col-md-2 col-md-offset-5">
    <%= link_to 'Aprovar candidatos', entrevistas_aprovar_path(entrevistas_id: @entrevistas_id), :class => "btn btn-default center-block" %><br>
  </div>

<br>

app/views/entrevistas/new.html.erb
<div class="container">
    <br>
    <h1 class="text-center">Nova entrevista</h1>
    <br><br>
    <%= render 'form' %>
    <div></div>
    <div class="col-md-2 col-md-offset-5">
         <div class="center-block">
            <%= link_to 'Voltar', entrevistas_path, :class=>"btn btn-sm btn-default center-block" %>
        </div>
    </div>
</div>

app/views/entrevistas/selection.html.erb
<%= form_tag("/entrevistas/selection", method: "post") do %>
  <h1>Selecionar campos</h1>
  <div class="row">
    <% @atributos.each do |a| %>
      <% if a == "id" %>
        <%= hidden_field_tag("exibir[]", a.to_sym) %>
      <% else %>
        <div class="col-md-2">
            <div class="input-group">
              <span class="input-group-addon">
                <%= check_box_tag("exibir[]", a.to_sym, autocomplete: "off") %>
              </span>
              <span class="input-group-addon"><%= a.camelcase %></span>
            </div><!-- /input-group -->
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="row">
  </div>
  <div class="row">
    <div class="col-md-2 col-md-offset-10">
      <%= submit_tag("Exibir" , role: "button", class: "btn btn-default" ) %>
    </div>
  </div>
<% end %>

app/views/entrevistas/show.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <p id="notice"><%= notice %></p>
    
    <h3>
      <!--Integração entre entrevista e candidato ainda não está feita -->
      <strong><%#= @entrevista.candidato %></strong>
    </h3>
    <br>
    <h3>Documentos</h3>
    <div class="row">
      <p class="col-md-3 "><strong>Entregou documentos:</strong> <%= @entrevista.entregou_documentos %></p>
      <p class="col-md-3 "><strong>Hisórico escolar:</strong> <%= @entrevista.historico_escolar %></p>
    </div>
    <br><br>
    <h3>Informações</h3>
    <div class="row">
      <p class="col-md-3 "><strong>Número de pessoas:</strong> <%= @entrevista.numero_de_pessoas%></p>
      <p class="col-md-3 "><strong>IPTU:</strong> <%= @entrevista.iptu %></p>
      <p class="col-md-3 "><strong>Número de veículos:</strong> <%= @entrevista.veiculos%></p>
    </div>
    <br>
    <h3>Renda</h3>
     <div class="row">
      <p class="col-md-3 "><strong>Holerite 1:</strong> <%= @entrevista.holerites_mes1%></p>
      <p class="col-md-3 "><strong>Holerite 2:</strong> <%= @entrevista.holerites_mes2%></p>
      <p class="col-md-3 "><strong>Holerite 3:</strong> <%= @entrevista.holerites_mes3 %></p>
      <p class="col-md-3 "><strong>Média :</strong> <%= Entrevista.media(@entrevista.holerites_mes1, @entrevista.holerites_mes2, @entrevista.holerites_mes3)%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Aposentadorias:</strong> <%= @entrevista.aposentadorias%></p>
      <p class="col-md-3 "><strong>Auxilios:</strong> <%= @entrevista.auxilios%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Renda bruta:</strong> <%= @entrevista.renda_bruta%></p>
      <p class="col-md-3 "><strong>Renda bruta per capita:</strong> <%= @entrevista.rbpc%></p>
    </div>
    <br><br>
    <h3>Gastos</h3>
    <div class="row">
      <p class="col-md-3 "><strong>Água 1:</strong> <%= @entrevista.agua_mes1%></p>
      <p class="col-md-3 "><strong>Água 2:</strong> <%= @entrevista.agua_mes2%></p>
      <p class="col-md-3 "><strong>Água 3:</strong> <%= @entrevista.agua_mes3 %></p>
      <p class="col-md-3 "><strong>Média :</strong> <%= Entrevista.media(@entrevista.agua_mes1, @entrevista.agua_mes2, @entrevista.agua_mes3)%></p>
    </div>
    <br>
     <div class="row">
      <p class="col-md-3 "><strong>Luz 1:</strong> <%= @entrevista.luz_mes1%></p>
      <p class="col-md-3 "><strong>Luz 2:</strong> <%= @entrevista.luz_mes2%></p>
      <p class="col-md-3 "><strong>Luz 3:</strong> <%= @entrevista.luz_mes3 %></p>
      <p class="col-md-3 "><strong>Média :</strong> <%= Entrevista.media(@entrevista.luz_mes1, @entrevista.luz_mes2, @entrevista.luz_mes3)%></p>
    </div>
     <br>
     <div class="row">
      <p class="col-md-3 "><strong>Internet/TV 1:</strong> <%= @entrevista.net_TV_mes1%></p>
      <p class="col-md-3 "><strong>Internet/TV 2:</strong> <%= @entrevista.net_TV_mes2%></p>
      <p class="col-md-3 "><strong>Internet/TV 3:</strong> <%= @entrevista.net_TV_mes3 %></p>
      <p class="col-md-3 "><strong>Média :</strong> <%= Entrevista.media(@entrevista.net_TV_mes1, @entrevista.net_TV_mes2, @entrevista.net_TV_mes3)%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Aluguel:</strong> <%= @entrevista.aluguel%></p>
      <p class="col-md-3 "><strong>Outros gastos:</strong> <%= @entrevista.outros_gastos%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Gastos totais:</strong> <%= @entrevista.gastos_totais%></p>
      <p class="col-md-3 "><strong>Renda líquida:</strong> <%= @entrevista.renda_liq%></p>
      <p class="col-md-3 "><strong>Renda líquida per capita:</strong> <%= @entrevista.rlpc%></p>
    </div>
    <br>
    <h3>Observações</h3>
    <div class="row">
      <p class="col-md-9 "><strong>Obs:</strong> <%= @entrevista.obs%></p>
    </div>
    <br><br>
    <h3>Status</h3>
    <div class="row">
      <p class="col-md-3 "><strong>Aprovado?:</strong> <%= @entrevista.aprovado%></p>
    </div>
    <br><br>
    <div>
      <%= link_to 'Editar', edit_entrevista_path(@entrevista), :class => "btn btn-default"%>
      <%= link_to 'Voltar', entrevistas_path, :class => "btn btn-default" %>
    </div>
</div>
</div>