config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users
  resources :users, only: :index
  root 'pages#home'
  get 'pages/home' => 'pages#home'
  get 'pages/dashboard' => 'pages#dashboard'
  
  get 'candidatos/selection' => 'candidatos#selection'
  post 'candidatos/selection' => 'candidatos#filter'
  get 'entrevistas/aprovar' => 'entrevistas#aprovar'
  
  get 'entrevistas/criteria_selection' => 'entrevistas#criteria_selection'
  post 'entrevistas/criteria_selection' => 'entrevistas#criteria_filter'
  
  resources :candidatos do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'entrevistas/selection' => 'entrevistas#selection'
  post 'entrevistas/selection' => 'entrevistas#filter'
  resources :entrevistas do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'formulario/:key' => 'pesquisas#matchKey'
  get 'pesquisas/enviar' => 'pesquisas#enviarForms'
  
  get 'pesquisas/selection' => 'pesquisas#selection'
  post 'pesquisas/selection' => 'pesquisas#filter'
  resources :pesquisas do
    collection { post :import }
    collection { get :addfile }
  end
  
  resources :candidatos
  get 'candidatos_pdfexport' => 'candidatos#pdfexport'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable ,:trackable
  
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
    before_action :require_admin
    
    def index
        @users = User.all
    end
end

app/helpers/user_helper.rb
module UserHelper
    def user_status(user)
        if user.admin? || user.invitation_accepted?
            content_tag(:span, '', class: 'glyphicon glyphicon-ok color-sucess')
        else 
           'Convite Pendente'
        end
    end
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu as instruções para confirmação?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Não recebeu instruções para desbloqueio?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar com #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_newsession.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label "E-mail" %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "Senha" %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label "Lembrar de mim" %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>