config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users
  resources :users, only: :index
  root 'pages#home'
  get 'pages/home' => 'pages#home'
  get 'pages/dashboard' => 'pages#dashboard'
  
  get 'candidatos/selection' => 'candidatos#selection'
  post 'candidatos/selection' => 'candidatos#filter'
  get 'entrevistas/aprovar' => 'entrevistas#aprovar'
  
  get 'entrevistas/criteria_selection' => 'entrevistas#criteria_selection'
  post 'entrevistas/criteria_selection' => 'entrevistas#criteria_filter'
  
  resources :candidatos do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'entrevistas/selection' => 'entrevistas#selection'
  post 'entrevistas/selection' => 'entrevistas#filter'
  resources :entrevistas do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'formulario/:key' => 'pesquisas#matchKey'
  get 'pesquisas/enviar' => 'pesquisas#enviarForms'
  
  get 'pesquisas/selection' => 'pesquisas#selection'
  post 'pesquisas/selection' => 'pesquisas#filter'
  resources :pesquisas do
    collection { post :import }
    collection { get :addfile }
  end
  
  resources :candidatos
  get 'candidatos_pdfexport' => 'candidatos#pdfexport'
  

end

app/models/candidato.rb
class Candidato < ActiveRecord::Base
    has_one :entrevista
    has_one :pesquisa
    
    #validates :inscricao, presence: true
    #validates :nome, presence: true
    #validates :rg, presence: true
    #validates :cpf, presence: true
    #validates :sexo, presence: true
    #validates :nascimento, presence: true
    #validates :email, presence: true
    #validates :endereco, presence: true
    #validates :bairro, presence: true
    #validates :cep, presence: true
    #validates :cidade, presence: true
    #validates :tipo_escola, presence: true
    #validates :escolaridade, presence: true
    #validates :nome_escola, presence: true
    #validates :transporte, presence: true
    #validates :ex_aluno, presence: true
    #validates :como_conheceu, presence: true
    #validates :data_inscricao, presence: true
    
    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
            csv << column_names #aqui que configura as informações que entram
            all.each do |candidato|
                csv << candidato.attributes.values_at(*column_names)
            end    
        end
    end
    
    require 'securerandom'
    
    def self.import(file)
        CSV.foreach(file.path, col_sep: ";", headers: true) do |row|
            #Candidato.create! row.to_hash
            hash = row.to_hash
            #conv = Candidato.new row.to_hash
            hash["nascimento"] = Date.strptime(hash["nascimento"], '%d/%m/%Y') 
            hash["data_inscricao"] = DateTime.strptime(hash["data_inscricao"], '%d/%m/%Y %H:%M')
            hash["key"] = SecureRandom.urlsafe_base64(10)
            Candidato.create! hash
        end
    end
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :set_candidato, only: [:show, :edit, :update, :destroy]
  # Incluimos a Lib que vamos criar para podermos chama-la no nosso método
  require './lib/generate_pdf'
  require 'prawn'
  before_action :require_user

  # GET /candidatos
  # GET /candidatos.json
  def index
    @candidatos = Candidato.all
    respond_to do |format|
      format.html
      format.csv { send_data @candidatos.to_csv }
      #format.xls 
    end
  end

  # GET /candidatos/1
  # GET /candidatos/1.json
  def show
    if not @candidato.pesquisa.nil?
      @pesquisa = @candidato.pesquisa
    end
  end

  # GET /candidatos/new
  def new
    @candidato = Candidato.new
  end

  def selection
    @atributos = Candidato.column_names
  end
  
  def filter
    @columns = params[:exibir]
    @candidatos = Candidato.select(params[:exibir])
    render :index2
  end
  # GET /candidatos/1/edit
  def edit
  end

  def addfile
  end

  def import
    Candidato.import(params[:file])
    redirect_to candidatos_path, notice: "CSV importado com sucesso."  
  end

  # POST /candidatos
  # POST /candidatos.json
  def create
    require 'securerandom'
    #candidato_params += ["key" => SecureRandom.urlsafe_base64(10)]
    @candidato = Candidato.new(candidato_params)
    respond_to do |format|
      if @candidato.save
        format.html { redirect_to @candidato, notice: 'Candidato was successfully created.' }
        format.json { render :show, status: :created, location: @candidato }
        #ApplicationMailer.sendMail(@candidato.email.to_s, "https://casd-adautobraz.c9users.io/".concat(@candidato.key.to_s))
      else
        format.html { render :new }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidatos/1
  # PATCH/PUT /candidatos/1.json
  def update
    respond_to do |format|
      if @candidato.update(candidato_params)
        format.html { redirect_to @candidato, notice: 'Candidato was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidato }
      else
        format.html { render :edit }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidatos/1
  # DELETE /candidatos/1.json
  def destroy
    @candidato.destroy
    respond_to do |format|
      format.html { redirect_to candidatos_url, notice: 'Candidato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # Criamos o método export para chamar a lib que gera o PDF e depois redirecionar o usuário para baixo o PDF
  def pdfexport
    
    GeneratePdf::candidato(Candidato.all.select { |cand| cand.entrevista && cand.entrevista.aprovado == true})
    #GeneratePdf::candidato(Candidato.all.map {|c| c })
    redirect_to '/candidatos_aprovados.pdf'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidato
      @candidato = Candidato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidato_params
      params.require(:candidato).permit(:candidato_id, :inscricao, :nome, :rg, :cpf, :sexo, :nascimento, :responsavel, :parentesco, :celular, :telefone, :email, :endereco, :bairro, :cep, :cidade, :especiais, :nec_especial, :tipo_escola, :escolaridade, :nome_escola, :trabalha, :profissao, :transporte, :internet, :ex_aluno, :como_conheceu, :data_inscricao, :facebook)
    end
end

app/helpers/candidatos_helper.rb
module CandidatosHelper
end

app/views/candidatos/_form.html.erb
<div class="container col-md-6 col-md-offset-3">
  <%= form_for(@candidato) do |f| %>
    <% if @candidato.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@candidato.errors.count, "error") %> prohibited this candidato from being saved:</h2>
  
        <ul>
        <% @candidato.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group row">
      <%= f.label :inscricao%>
      <%= f.number_field :inscricao, :class=>"form-control" %>
    </div>
    
    <div class="form-group row">
      <%= f.label :nome %><br>
      <%= f.text_field :nome, :class=>"form-control" %>
    </div>
    
    <div class="form-group row">
      <%= f.label :rg %><br>
      <%= f.text_field :rg, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :cpf %><br>
      <%= f.text_field :cpf, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :sexo %><br>
      <%= f.text_field :sexo, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :nascimento %><br>
      <%= f.date_field :nascimento, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :responsavel %><br>
      <%= f.text_field :responsavel, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :parentesco %><br>
      <%= f.text_field :parentesco, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :celular %><br>
      <%= f.telephone_field :celular, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :telefone %><br>
      <%= f.telephone_field :telefone, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :email %><br>
      <%= f.text_field :email, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :endereco %><br>
      <%= f.text_field :endereco, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :bairro %><br>
      <%= f.text_field :bairro, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :cep %><br>
      <%= f.text_field :cep, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :cidade %><br>
      <%= f.text_field :cidade, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :especiais %><br>
      <%= f.check_box :especiais, :class=>"form-check" %>
    </div>
    <div class="form-group row">
      <%= f.label :nec_especial %><br>
      <%= f.text_field :nec_especial, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :tipo_escola %><br>
      <%= f.text_field :tipo_escola, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :escolaridade %><br>
      <%= f.text_field :escolaridade, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :nome_escola %><br>
      <%= f.text_field :nome_escola, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :trabalha %><br>
      <%= f.check_box :trabalha, :class=>"form-check" %>
    </div>
    <div class="form-group row">
      <%= f.label :profissao %><br>
      <%= f.text_field :profissao, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :transporte %><br>
      <%= f.text_field :transporte, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :internet %><br>
      <%= f.check_box :internet, :class=>"form-check" %>
    </div>
    <div class="form-group row">
      <%= f.label :ex_aluno %><br>
      <%= f.text_field :ex_aluno, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :como_conheceu %><br>
      <%= f.text_field :como_conheceu, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :data_inscricao %><br>
      <%= f.date_field :data_inscricao, :class=>"form-control" %>
    </div>
    <div class="form-group row">
      <%= f.label :facebook %><br>
      <%= f.text_field :facebook, :class=>"form-control" %>
    </div>
    <% require 'securerandom' %>
    <%= f.hidden_field :key, :value =>  SecureRandom.urlsafe_base64(10)%>

    <div class="form-group row">
      <%= f.submit 'Salvar', :class => 'btn btl-lg btn-primary col-md-4 col-md-offset-4' %>
    </div>
  <% end %>
</div>

app/views/candidatos/addfile.html.erb
<div class="container">
    <br>
    <h1 class="text-center">Importar lista de candidatos</h1>
    <br><br>
    <%= form_tag import_candidatos_path, multipart: true do %>
      <div class="form-group col-md-4 col-md-offset-4 ">
        <%= file_field_tag :file, :class => 'form-control' %><br>
        <%= submit_tag "Importar", :class => 'btn btn-primary center-block'  %>
      </div>
    <% end %>
</div>

app/views/candidatos/edit.html.erb
<div class="container">
    <br>
    <h1 class="text-center">Editar candidato</h1>
    <br><br>
    <%= render 'form' %>
    <div></div>
    <div class="col-md-2 col-md-offset-5">
         <div class="center-block">
            <%= link_to 'Voltar', candidatos_path, :class=>"btn btn-sm btn-default center-block" %>
        </div>
    </div>
</div>

app/views/candidatos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
 
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
  <script>
    $(document).ready(function() {
    $('#candidatosTable').DataTable();
  });
  </script>
  
  <h1>Listando Candidatos | <%= link_to "Selecionar Colunas", candidatos_selection_path , role: "button", class: "btn btn-default" %></h1>
  <br><br>
  <div>
    <div class="btn-group" role="group" aria-label="...">
      <%= link_to 'Novo Candidato', new_candidato_path, :class => "btn btn-default" %>
      <%= link_to 'Importar Lista CSV', addfile_candidatos_path, :class => "btn btn-default" %>
      <%= link_to "Exportar CSV", candidatos_path(format: "csv"),  :class => "btn btn-default" %>
      <% link_to 'Exportar Lista PDF', candidatos_pdfexport_path, :class => "btn btn-default" %>
    </div>
  </div>
  <br>
      <table class="table table-striped" id="candidatosTable" >
        <thead>
          <tr>
            <!--<th>Inscricao</th>-->
            <th>Nome</th>
            <th>Rg</th>
            <th>Cpf</th>
            <th>Sexo</th>
            <th>Nascimento</th>
            <!--<th>Responsavel</th>
            <th>Parentesco</th>
            <th>Celular</th>
            <th>Telefone</th>-->
            <th>Email</th>
            <th>Endereco</th>
            <th>Bairro</th>
            <!--<th>Cep</th>-->
            <th>Cidade</th>
            <!--<th>Especiais</th>
            <th>Nec especial</th>
            <th>Tipo escola</th>
            <th>Escolaridade</th>
            <th>Nome escola</th>
            <th>Trabalha</th>
            <th>Profissao</th>
            <th>Transporte</th>
            <th>Internet</th>
            <th>Ex aluno</th>
            <th>Como conheceu</th>
            <th>Data inscricao</th>
            <th>Facebook</th>-->
            <th> </th>
            <th> </th>
            <th> </th>
          </tr>
        </thead>
      
        <tbody>
          <% @candidatos.each do |candidato| %>
            <tr>
              <!--<td><%= candidato.inscricao %></td>-->
              <td><%= candidato.nome %></td>
              <td><%= candidato.rg %></td>
              <td><%= candidato.cpf %></td>
              <td><%= candidato.sexo %></td>
              <td><%= candidato.nascimento %></td>
              <!--<td><%= candidato.responsavel %></td>
              <td><%= candidato.parentesco %></td>
              <td><%= candidato.celular %></td>
              <td><%= candidato.telefone %></td>-->
              <td><%= candidato.email %></td>
              <td><%= candidato.endereco %></td>
              <td><%= candidato.bairro %></td>
              <!--<td><%= candidato.cep %></td>-->
              <td><%= candidato.cidade %></td>
              <!--<td><%= candidato.especiais %></td>
              <td><%= candidato.nec_especial %></td>
              <td><%= candidato.tipo_escola %></td>
              <td><%= candidato.escolaridade %></td>
              <td><%= candidato.nome_escola %></td>
              <td><%= candidato.trabalha %></td>
              <td><%= candidato.profissao %></td>
              <td><%= candidato.transporte %></td>
              <td><%= candidato.internet %></td>
              <td><%= candidato.ex_aluno %></td>
              <td><%= candidato.como_conheceu %></td>
              <td><%= candidato.data_inscricao %></td>
              <td><%= candidato.facebook %></td>-->
              <td><%= link_to 'Ver', candidato, :class => "btn btn-sm btn-default" %></td>
              <td><%= link_to 'Editar', edit_candidato_path(candidato), :class => "btn btn-sm  btn-default"  %></td>
              <td><%= link_to 'Excluir', candidato, method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-sm btn-default" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <br>
  
  
  <div class="btn-group" role="group" aria-label="...">
    <%= link_to 'Novo Candidato', new_candidato_path, :class => "btn btn-default" %>
    <%= link_to 'Importar Lista CSV', addfile_candidatos_path, :class => "btn btn-default" %>
    <%= link_to "Exportar CSV", candidatos_path(format: "csv"),  :class => "btn btn-default" %>
    <% link_to 'Exportar Lista PDF', candidatos_pdfexport_path, :class => "btn btn-default" %>
    <%= link_to 'Enviar formulários', pesquisas_enviar_path, :class => "btn btn-default center-block" %><br>
  </div>
  <br><br><br><br><br>
</div>

app/views/candidatos/index2.html.erb
<p id="notice"><%= notice %></p>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>


<h1>Listando Candidatos | <%= link_to "Selecionar Colunas", candidatos_selection_path , role: "button", class: "btn btn-default" %></h1>

<table id="candidatosTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <% @columns.each do |s| %>
        <% if s!="id" %>
          <th><%= s.camelcase %></th>
        <% end %>
      <% end %>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @candidatos.each do |candidato| %>
      <tr>
        <% @columns.each do |s| %>
          <% if s!="id" %>
            <td><%= candidato[s.to_sym] %></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', candidato, role: "button", class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Edit', edit_candidato_path(candidato), role: "button", class: "btn btn-info btn-xs" %></td>
        <td><%= link_to 'Destroy', candidato, method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Candidato', new_candidato_path , role: "button", class: "btn btn-default" %>
<%= link_to 'Importar Lista CSV', addfile_candidatos_path , role: "button", class: "btn btn-default" %>

<script>
  $(document).ready(function() {
  $('#candidatosTable').DataTable();
});
</script>

app/views/candidatos/new.html.erb
<div class="container">
    <br>
    <h1 class="text-center">Novo candidato</h1>
    <br><br>
    <%= render 'form' %>
    <div></div>
    <div class="col-md-2 col-md-offset-5">
         <div class="center-block">
            <%= link_to 'Voltar', candidatos_path, :class=>"btn btn-sm btn-default center-block" %>
        </div>
    </div>
</div>

app/views/candidatos/selection.html.erb
<%= form_tag("/candidatos/selection", method: "post") do %>
  <h1>Selecionar campos</h1>
  <div class="row">
    <% @atributos.each do |a| %>
      <% if a == "id" %>
        <%= hidden_field_tag("exibir[]", a.to_sym) %>
      <% else %>
        <div class="col-md-2">
            <div class="input-group">
              <span class="input-group-addon">
                <%= check_box_tag("exibir[]", a.to_sym, autocomplete: "off") %>
              </span>
              <span class="input-group-addon"><%= a.camelcase %></span>
            </div><!-- /input-group -->
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="row">
  </div>
  <div class="row">
    <div class="col-md-2 col-md-offset-10">
      <%= submit_tag("Exibir" , role: "button", class: "btn btn-default" ) %>
    </div>
  </div>
<% end %>

app/views/candidatos/show.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <p id="notice"><%= notice %></p>
    
    <h3>
      <strong><%= @candidato.nome %></strong>
    </h3>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Inscrição:</strong> <%= @candidato.inscricao %></p>
      <p class="col-md-3 "><strong>Sexo:</strong> <%= @candidato.sexo %></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Nascimento:</strong> <%= @candidato.nascimento%></p>
      <p class="col-md-3 "><strong>RG:</strong> <%= @candidato.rg %></p>
      <p class="col-md-3 "><strong>CPF:</strong> <%= @candidato.cpf%></p>
    </div>
    <br>
     <div class="row">
      <p class="col-md-3 "><strong>Responsável:</strong> <%= @candidato.responsavel%></p>
      <p class="col-md-3 "><strong>Parentesco:</strong> <%= @candidato.parentesco %></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Celular:</strong> <%= @candidato.celular%></p>
      <p class="col-md-3 "><strong>Telefone:</strong> <%= @candidato.telefone%></p>
      <p class="col-md-3 "><strong>Email:</strong> <%= @candidato.email%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Endereço:</strong> <%= @candidato.endereco%></p>
      <p class="col-md-3 "><strong>Bairro:</strong> <%= @candidato.bairro%></p>
      <p class="col-md-3 "><strong>CEP:</strong> <%= @candidato.cep%></p>
      <p class="col-md-3 "><strong>Cidade:</strong> <%= @candidato.cidade%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Especiais:</strong> <%= @candidato.especiais%></p>
      <p class="col-md-3 "><strong>Necessidades especiais:</strong> <%= @candidato.nec_especial%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Tipo escola:</strong> <%= @candidato.tipo_escola%></p>
      <p class="col-md-3 "><strong>Escolaridade:</strong> <%= @candidato.escolaridade%></p>
      <p class="col-md-3 "><strong>Nome da escola:</strong> <%= @candidato.nome_escola%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Trabalha:</strong> <%= @candidato.trabalha%></p>
      <p class="col-md-3 "><strong>Profissao:</strong> <%= @candidato.profissao%></p>
      <p class="col-md-3 "><strong>Transporte:</strong> <%= @candidato.transporte%></p>
      <p class="col-md-3 "><strong>Internet:</strong> <%= @candidato.internet%></p>
    </div>
    <br>
    <div class="row">
      <p class="col-md-3 "><strong>Ex-aluno?:</strong> <%= @candidato.ex_aluno%></p>
      <p class="col-md-3 "><strong>Como conheceu:</strong> <%= @candidato.como_conheceu%></p>
      <p class="col-md-3 "><strong>Data inscrição:</strong> <%= @candidato.data_inscricao%></p>
      <p class="col-md-3 "><strong>Facebook:</strong> <%= @candidato.facebook%></p>
    </div>
    <br>
    <div>
      <%= link_to 'Editar', edit_candidato_path(@candidato), :class => "btn btn-default"%>
      <%= link_to 'Criar entrevista', new_entrevista_path(:candidato_id => @candidato.id ), :class => "btn btn-default"%>
      <% if not @pesquisacriada.nil? %>
        <%= link_to 'Ver formulário', edit_pesquisa_path(:id => @pesquisa.id ), :class => "btn btn-default"%>
      <% else %>
        <%= link_to 'Criar formulário', new_pesquisa_path(:candidato_id => @candidato.id), :class => "btn btn-default"%>
      <% end %>
      <%= link_to 'Voltar', candidatos_path, :class => "btn btn-default" %>
    </div>
  </div>
</div>