config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users
  resources :users, only: :index
  root 'pages#home'
  get 'pages/home' => 'pages#home'
  get 'pages/dashboard' => 'pages#dashboard'
  
  get 'candidatos/selection' => 'candidatos#selection'
  post 'candidatos/selection' => 'candidatos#filter'
  get 'entrevistas/aprovar' => 'entrevistas#aprovar'
  
  get 'entrevistas/criteria_selection' => 'entrevistas#criteria_selection'
  post 'entrevistas/criteria_selection' => 'entrevistas#criteria_filter'
  
  resources :candidatos do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'entrevistas/selection' => 'entrevistas#selection'
  post 'entrevistas/selection' => 'entrevistas#filter'
  resources :entrevistas do
    collection { post :import }
    collection { get :addfile }
  end
  
  get 'formulario/:key' => 'pesquisas#matchKey'
  get 'pesquisas/enviar' => 'pesquisas#enviarForms'
  
  get 'pesquisas/selection' => 'pesquisas#selection'
  post 'pesquisas/selection' => 'pesquisas#filter'
  resources :pesquisas do
    collection { post :import }
    collection { get :addfile }
  end
  
  resources :candidatos
  get 'candidatos_pdfexport' => 'candidatos#pdfexport'
  

end

app/views/layouts/_topnavbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "CESDt.png", class: "navbar-left", size: "150x60"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %> <%# %> 
        <li><%= link_to 'Dashboard', pages_dashboard_path %></li>
        <li><%= link_to 'Entrevistas', entrevistas_path %></li>
        <li><%= link_to 'Candidatos', candidatos_path %></li>
        <li><%= link_to 'Pesquisas', pesquisas_path %></li>
        <% if current_user.admin? %>
        <li><%= link_to 'Usuários', users_path %></li>
        <% end %>
        <li><%= link_to 'Minha Conta', edit_user_registration_path %></li>
        <li><%= link_to 'Sair', destroy_user_session_path, :method => :delete %></li>
      <% else %> <%# %>  
      <ul class="nav navbar-nav"><%# %> 
        <li><%= link_to 'Entrar', new_user_session_path %></li> <%# %> 
      </ul> <%# %> 
      <% end %> <%# %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Casd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Wrapper-->
  <div id="wrapper"> 

    <!-- Page wraper -->
    <div id="page-wrapper" class="gray-bg">

        <!-- Page wrapper -->
        <%= render 'layouts/topnavbar' %>
        
        <!-- Notices -->
        <% if notice %>
        <div class="alert alert-info alert-dismissable">
          <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
          <%= notice %>
        </div>
        <% end %>
        <!-- Main view  -->
        <div class="container">
          <%= yield %>
        </div>
        <!-- Footer -->
        <% #render 'layouts/footer' %>
    </div>
    <!-- End page wrapper-->
  </div>
  <!-- End wrapper-->
</body>
</html>